<?php
/**
 * Implements hook_node_view().
 */
function velvetrope_node_view($node, $view_mode, $langcode) {
	if($GLOBALS['user']->uid){
		
		db_insert('velvetrope_entries')
			->fields(array('ipaddress' => $_SERVER['REMOTE_ADDR'], 'pagenid' => $node->nid, 'dateviewed' => REQUEST_TIME))
			->execute();
		$secondsinday = 86400;
		
		$result = db_select('velvetrope_entries', 've')
		->fields('ve')
		->condition('ipaddress', $_SERVER['REMOTE_ADDR'], '=')
		->orderby('dateviewed', 'DESC')
		->execute()
		->fetchAll();
		
		if(count($result) > 3)
		{
			drupal_set_message(t('here again?'));
		}		
		else
		{
			drupal_set_message(t('that\'s another.'));
		}
	}
}

