<?php
/**
 * Implements hook_node_view().
 */
function velvetrope_init() {
	//velvetrope_delete_entries();	
	if(current_path() == 'user' || current_path() == variable_get('velvetrope_redirectto')){	
		return;
	}
	if(user_is_anonymous()){			
		$numviews = velvetrope_get_entries();
		$mustregister = count($numviews) > variable_get('velvetrope_anonymousviews') ? 1 : 0;			
		if($mustregister == 0){
			if(velvetrope_has_expired() == TRUE){
				$mustregister = 0;
				velvetrope_delete_entries();
			}
		}	
		velvetrope_insert_entry($mustregister);
		if($mustregister == 1){
			drupal_goto(variable_get('velvetrope_redirectto'));
		}			
	}
}

function velvetrope_get_entries(){
	return db_select('velvetrope_entries', 've')
			->fields('ve')
			->condition('ipaddress', $_SERVER['REMOTE_ADDR'], '=')
			->orderby('dateviewed', 'DESC')
			->execute()
			->fetchAll();	
}

function velvetrope_delete_entries(){
	return db_delete('velvetrope_entries')
		->condition('ipaddress', $_SERVER['REMOTE_ADDR'])
		->execute();
}

function velvetrope_get_lastdateviewed(){
	return db_select('velvetrope_entries', 've')
			->fields('ve')
			->condition('ipaddress', $_SERVER['REMOTE_ADDR'])
			->orderby('dateviewed', 'DESC')
			->execute()
			->fetchObject()->dateviewed;
}

function velvetrope_insert_entry($mustregister){
	db_insert('velvetrope_entries')
		->fields(array('ipaddress' => $_SERVER['REMOTE_ADDR'], 'dateviewed' => REQUEST_TIME, 'mustregister' => $mustregister))
		->execute();
}

function velvetrope_has_expired(){
	return FALSE;
	
	$secondsinday = 86400;
	$dateviewed = velvetrope_get_lastdateviewed();
	return $secondsinday * variable_get('velvetrope_timespan');	
	$timespan = velvetrope_calculate_timespan();
	if(REQUEST_TIME - $dateviewed > $timespan){	
		return TRUE;
	}
	return FALSE;
}
/**
 * Implements hook_menu().
 */
function velvetrope_menu() {
  $items['admin/config/velvetrope'] = 
	array(
		'title' => 'velvetrope message configure',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('velvetrope_form'),
		'access arguments' => array('administer users'),
		'type' => MENU_NORMAL_ITEM,
		'menu_name' => 'velvetrope',
	);
 
  return $items;
}
  
 /**
 * Admin form to configurable velvetrope
 */
function velvetrope_form($form, &$form_state) {
	$form['velvetrope_anonymousviews'] = array(
		'#type' => 'textarea',
		'#title' => t('Anonymous Views'),
		'#rows' => 1,
		'#required' => TRUE,
		'#default_value' => variable_get('velvetrope_anonymousviews', '3')
	);
	
	$form['velvetrope_timespan'] = array(
		'#type' => 'textarea',
		'#title' => t('Time Span'),
		'#rows' => 1,
		'#required' => TRUE,
		'#default_value' => variable_get('velvetrope_timespan', '1')
	);
	
	$form['velvetrope_redirectto'] = array(
		'#type' => 'textarea',
		'#title' => t('Velvet Rope Redirect Page'),
		'#rows' => 1,
		'#required' => TRUE,
		'#default_value' => variable_get('velvetrope_redirectto', 'user/register'),
	);
	
	return system_settings_form($form);
}
